name = "ConstrainedControl"
uuid = "5933d0f4-dc4a-46ce-a189-54b4465bd7a4"
authors = ["Jan Bruedigam"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
